services:
    nginx:
        image: nginx:1.29.1-alpine3.22
        container_name: '${PROJECT_NAME}_nginx'
        volumes:
            - './local/nginx/mime.types:/etc/nginx/mime.types'
            - './local/nginx/nginx.conf:/etc/nginx/nginx.conf'
            - './local/nginx/default.conf:/etc/nginx/conf.d/default.conf'
            - './local/nginx/search.conf:/etc/nginx/conf.d/search.conf'
            - '..:/var/www/html:cached'
        working_dir: /var/www/html
        ports:
            - '80:80'
            - '443:443'
        networks:
            local:
                aliases:
                    - laravel.localdev
                    - laravel.search.localdev

    php:
        build: ./local/php
        container_name: '${PROJECT_NAME}_php'
        ports:
            - '9000:9000'
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
        volumes:
            - '../:/var/www/html:cached'
            - './backup/db:/db'
        working_dir: /var/www/html
        networks:
            - local

    nodejs:
        build: ./local/nodejs
        container_name: '${PROJECT_NAME}_nodejs'
        working_dir: /var/www/html
        volumes:
            - '..:/var/www/html'
            - /var/www/html/node_modules
        tty: true
        ports:
            - '5173:5173'
        networks:
            local:
                aliases:
                    - laravel.localdev

    database:
        image: 'mariadb:11.4.5'
        container_name: '${PROJECT_NAME}_db'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: laravel_db
        ports:
            - '3306:3306'
        volumes:
            - './db_data:/var/lib/mysql:delegated'
            - ./backup/db:/db
        networks:
            - local

    opensearch-node1:
        image: 'opensearchproject/opensearch:2.9.0'
        container_name: '${PROJECT_NAME}_opensearch-node1'
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node1
            - 'discovery.seed_hosts=opensearch-node1,opensearch-node2'
            - 'cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2'
            - bootstrap.memory_lock=true
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - DISABLE_SECURITY_PLUGIN=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - './opensearch-data1:/usr/share/opensearch/data'
            - './local/opensearch.yml:/usr/share/opensearch/config/opensearch.yml'
        ports:
            - '9200:9200'
            - '9600:9600'
        networks:
            local:
                aliases:
                    - laravel.search.localdev

    opensearch-node2:
        image: 'opensearchproject/opensearch:2.9.0'
        container_name: '${PROJECT_NAME}_opensearch-node2'
        environment:
            - cluster.name=opensearch-cluster
            - node.name=opensearch-node2
            - 'discovery.seed_hosts=opensearch-node1,opensearch-node2'
            - 'cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2'
            - bootstrap.memory_lock=true
            - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
            - DISABLE_INSTALL_DEMO_CONFIG=true
            - DISABLE_SECURITY_PLUGIN=true
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        volumes:
            - './opensearch-data2:/usr/share/opensearch/data'
            - './local/opensearch.yml:/usr/share/opensearch/config/opensearch.yml'
        networks:
            local:
                aliases:
                    - laravel.search.localdev

    opensearch-dashboards:
        image: 'opensearchproject/opensearch-dashboards:2.9.0'
        container_name: '${PROJECT_NAME}_opensearch-dashboards'
        ports:
            - '5601:5601'
        expose:
            - '5601'
        environment:
            - OPENSEARCH_HOSTS=["http://opensearch-node1:9200","http://opensearch-node2:9200"]
            - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
        networks:
            local:
                aliases:
                    - laravel.search.localdev

    mailhog:
        container_name: '${PROJECT_NAME}_mailhog'
        image: mailhog/mailhog
        restart: always
        platform: linux/amd64
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - local

    redis:
        container_name: '${PROJECT_NAME}_redis'
        image: 'redis:8.0-alpine3.21'
        logging:
            options:
                max-size: 10m
                max-file: '3'
        networks:
            - local

networks:
    local:
volumes:
    db_data:
    opensearch-data1:
    opensearch-data2:
